export const SHOW_HIDE_CART = 'SHOW_HIDE_CART'
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_ITEM = 'REMOVE_ITEM'
export const TOTAL_PRICE = 'TOTAL_PRICE'
export const QUANT_PLUS = 'QUANT_PLUS'
export const QUANT_SUBS = 'QUANT_SUBS'