import Head from 'next/head'
import Image from 'next/image'


export default function Home() {
  return (
    <div >
      <Head>
        <title>Coderio challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='flex flex-col justify-center items-center w-screen h-screen bg-red'>
        <input type="text" placeholder='asd' />
        <h1>ASD</h1>
      </div>

    </div>
  )
}
